name: ptx_dyn_GPU
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alabaster=0.7.12
  - arrow=1.2.3
  - astroid=2.14.2
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - attrs=23.1.0
  - autopep8=1.6.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.11.0
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - conda=23.3.1
  - cookiecutter=2.5.0
  - cryptography=41.0.7
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.7
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - executing=0.8.3
  - expat=2.5.0
  - flake8=6.0.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.25.0
  - ipython=8.20.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jellyfish=1.0.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_pygments=0.2.2
  - keyring=23.13.1
  - krb5=1.20.1
  - lazy-object-proxy=1.6.0
  - ld_impl_linux-64=2.38
  - libclang13=14.0.6
  - libcups=2.4.2
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=2.0.4
  - more-itertools=10.1.0
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.35
  - nss=3.89.1
  - numpydoc=1.5.0
  - openssl=3.0.12
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.10.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pylint=2.16.2
  - pylint-venv=2.3.0
  - pyls-spyder=0.4.0
  - pyopenssl=23.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.2
  - python-slugify=5.0.2
  - pytoolconfig=1.2.6
  - pytz=2023.3.post1
  - pyxdg=0.27
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qdarkstyle=3.0.2
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtconsole=5.4.2
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rich=13.3.5
  - rope=1.7.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - secretstorage=3.3.1
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.3
  - spyder-kernels=2.4.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomlkit=0.11.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - ujson=5.4.0
  - unidecode=1.2.0
  - urllib3=1.26.18
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.41.2
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - xz=5.4.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - contourpy==1.2.0
      - cramjam==2.8.2
      - cycler==0.12.1
      - diffrax==0.5.0
      - equinox==0.11.3
      - fastparquet==2024.2.0
      - flatbuffers==23.5.26
      - fonttools==4.47.2
      - fsspec==2024.2.0
      - gast==0.5.4
      - google-auth==2.28.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.1
      - gviz-api==1.10.0
      - h5py==3.10.0
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - lineax==0.0.4
      - markdown==3.5.2
      - matplotlib==3.8.2
      - ml-dtypes==0.2.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.3.4.1
      - nvidia-cuda-cupti-cu12==12.3.101
      - nvidia-cuda-nvcc-cu12==12.3.107
      - nvidia-cuda-nvrtc-cu12==12.3.107
      - nvidia-cuda-runtime-cu12==12.3.101
      - nvidia-cudnn-cu12==8.9.7.29
      - nvidia-cufft-cu12==11.0.12.1
      - nvidia-cusolver-cu12==11.5.4.101
      - nvidia-cusparse-cu12==12.2.0.103
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optimistix==0.0.6
      - pandas==2.2.1
      - pillow==10.2.0
      - pip==23.3.2
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyarrow==15.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pynvml==11.4.1
      - pyparsing==3.1.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scalene==1.5.34
      - scipy==1.11.4
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-profile==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - typeguard==2.13.3
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - werkzeug==3.0.1
